[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
fundamentals = {path = "../fundamentals"}
backend = {path = "../backend"}
indexmap = "1.9.1"
